### ISSUE TITLE
Incompatible versions in requirements

### ISSUE THREAD

**Issue by wilko77** [data61/anonlink-client#24]
I just noticed in the logs:
```
ERROR: nbval 0.9.4 has requirement coverage<5, but you'll have coverage 5.0.3 which is incompatible.
```
https://dev.azure.com/data61/Anonlink/_build/results?buildId=1267&view=logs&j=f3c463f8-ccf0-5b04-abcc-1d347c67f7c1&t=c5dc43ee-d867-5244-d1aa-935f5657afd6&l=144

more info [here](https://github.com/computationalmodelling/nbval/issues/129)
It seems that it only creates an issue if you want to send a coverage report for your tested notebook. We currently don't do that, so we should be fine.

I saw that they already fixed that in their current master, but that change is not released, yet.

**Comment by JoyceXinyueWang** [comment]
The new version 0.9.5 is released to address this issue. So we can close it
