### ISSUE TITLE
release 0.1.2 is broken

### ISSUE THREAD

**Issue by wilko77** [data61/anonlink-client#53]
`setup.py` is missing the blocklib dependency.

Quickfix until next release:
`pip install blocklib`

**Comment by JoyceXinyueWang** [comment]
Isn't blocklib dependency here:
https://github.com/data61/anonlink-client/blob/master/setup.py#L6

**Comment by wilko77** [comment]
not in the current release. https://github.com/data61/anonlink-client/blob/v0.1.2/setup.py

**Comment by JoyceXinyueWang** [comment]
Resolved
